In [57]:
import torch
inputs = torch.tensor(
    [[0.43, 0.15, 0.89],  # your
     [0.55, 0.87, 0.66],  # journey 
     [0.32, 0.75, 0.48],  # starts
     [0.91, 0.27, 0.63],  # with
     [0.18, 0.59, 0.72],  # one
     [0.37, 0.82, 0.53]]  # step
)

In [58]:
query  = inputs[1]; #we are looking just at journey

attn_scores = torch.empty(inputs.shape[0]) #will make a vector filled with garbage values, and dimensions of inputs which is 3.

for i,x_i in enumerate(inputs): # i is the index, and xi are all the input tokens. 
    attn_scores[i] = torch.dot(query, x_i)

attn_scores

tensor([0.9544, 1.4950, 1.1453, 1.1512, 1.0875, 1.2667])

In [59]:
new_attn_scores = torch.softmax(attn_scores, dim=0) #softmax to normalize the attention scores
new_attn_scores
print(new_attn_scores.sum()) #should be 1.0


tensor(1.0000)


In [60]:
print(new_attn_scores)

tensor([0.1307, 0.2243, 0.1581, 0.1591, 0.1493, 0.1785])


In [63]:
query = inputs[1]  # we are looking just at 'journey'
newtensor = torch.zeros(query.shape)

for i,x_i in enumerate(inputs):  # iterate over the transposed inputs
    newtensor += new_attn_scores[i] * x_i  # multiply each column by the corresponding attention score

In [64]:

newtensor

tensor([0.4679, 0.6108, 0.6426])