In [1]:
import torch
inputs = torch.tensor(
    [[0.43, 0.15, 0.89],  # your
     [0.55, 0.87, 0.66],  # journey 
     [0.32, 0.75, 0.48],  # starts
     [0.91, 0.27, 0.63],  # with
     [0.18, 0.59, 0.72],  # one
     [0.37, 0.82, 0.53]]  # step
)

In [2]:
query  = inputs[1]; #we are looking just at journey

attn_scores = torch.empty(inputs.shape[0]) #will make a vector filled with garbage values, and dimensions of inputs which is 3.

for i,x_i in enumerate(inputs): # i is the index, and xi are all the input tokens. 
    attn_scores[i] = torch.dot(query, x_i)

attn_scores

tensor([0.9544, 1.4950, 1.1453, 1.1512, 1.0875, 1.2667])

In [3]:
new_attn_scores = torch.softmax(attn_scores, dim=0) #softmax to normalize the attention scores
new_attn_scores
print(new_attn_scores.sum()) #should be 1.0


tensor(1.0000)


In [4]:
print(new_attn_scores)

tensor([0.1307, 0.2243, 0.1581, 0.1591, 0.1493, 0.1785])


In [5]:
query = inputs[1]  # we are looking just at 'journey'
newtensor = torch.zeros(query.shape)

for i,x_i in enumerate(inputs):  # iterate over the transposed inputs
    newtensor += new_attn_scores[i] * x_i  # multiply each column by the corresponding attention score

In [6]:
newtensor

tensor([0.4679, 0.6108, 0.6426])

In [7]:
'''
actual_attn_scores = torch.empty(6,6)  # will make a vector filled with garbage values, and dimensions of inputs which is 3.

for i,x_i in enumerate(inputs):
    for(j, x_j) in enumerate(inputs):
        actual_attn_scores[i,j] = torch.dot(x_i, x_j)  # calculate the dot product between each pair of input tokens

'''     

'\nactual_attn_scores = torch.empty(6,6)  # will make a vector filled with garbage values, and dimensions of inputs which is 3.\n\nfor i,x_i in enumerate(inputs):\n    for(j, x_j) in enumerate(inputs):\n        actual_attn_scores[i,j] = torch.dot(x_i, x_j)  # calculate the dot product between each pair of input tokens\n\n'

In [ ]:
#for loops are slower so we use, transpose and matrix multiplication.

actual_attn_scores = inputs @ inputs.T  # matrix multiplication to get the attention scores for all pairs of tokens
actual_attn_scores = torch.softmax(actual_attn_scores, dim=-1)  # apply dim=-1 we are normalizing on the column, so when u add all the values of the column it results in 1.
actual_attn_scores

tensor([[0.1894, 0.1810, 0.1372, 0.1881, 0.1562, 0.1481],
        [0.1307, 0.2243, 0.1581, 0.1591, 0.1493, 0.1785],
        [0.1331, 0.2125, 0.1655, 0.1499, 0.1575, 0.1815],
        [0.1650, 0.1934, 0.1356, 0.2239, 0.1330, 0.1492],
        [0.1523, 0.2017, 0.1584, 0.1478, 0.1670, 0.1727],
        [0.1303, 0.2176, 0.1646, 0.1496, 0.1557, 0.1824]])

In [17]:
print(sum(actual_attn_scores[3]))  # should be 1.0 for the 'journey' row

tensor(1.)
